name: Call Reusable Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Reusable Build
    uses: ./.github/workflows/reusable-build.yml

    with:
      app_name: "my-web-app"
      environment: "production"

    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  print-version:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Print build version
        run: |
          echo "Build version is ${{ needs.build.outputs.build_version}}"
  
