name: My Secrets Demo

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  secrets-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check if secrets exists
        env:
          MY_SECRET_MESSAGE: ${{ secrets.MY_SECRET_MESSAGE }}
        run: |
          #!/bin/bash
          if [ -n "MY_SECRET_MESSAGE" ]; then
            echo "The secret is set: true"
          else:
            echo "The secret is set: false"
            exit 1
          fi

      - name: GitHub secret masking behaviour
        env:
          MY_SECRET_MESSAGE: ${{ secrets.MY_SECRET_MESSAGE }}
        run: |
          echo "If printed, GitHub masks the secret value in logs:"
          echo "$MY_SECRET_MESSAGE"
