name: Smart Triggers

on:
  push:
    branches:
      - main
      - 'release/*'
    paths:
      - 'src/**'
      - 'app/**'

jobs:
  run-if-app-changed:
    runs-on: ubuntu-latest

    steps:
      - name: Run Job
        run: echo "Application code changed"
